Разрешение СЛАУ с трёх диагональной матрицой и ненулевыми главными минорами.

In [99]:
import numpy as np

In [100]:
def sol(m, b):
    a = m.copy() #Чтобы не трогать переданный массив
    for i in range(a.shape[0]-1):
        u = np.argmax(np.abs(a[i:,i])) + i #поиск максимального элемента в текущем столбце
        sec_a = a[i].copy()
        sec_b = b[i].copy()
        a[i] = a[u]
        b[i] = b[u]
        a[u] = sec_a
        b[u] = sec_b
        b[i] = b[i]/a[i, i]  
        a[i] = a[i]/a[i, i] #Нормировка к ведущему элементу
        
        gi = a[i+1:,i]
        b[i+1:] -= np.tensordot(gi,b[i],axes=0)
        a[i+1:] -= np.tensordot(gi,a[i],axes=0)
        
    b[-1]=b[-1]/a[-1][-1]
    a[-1]=a[-1]/a[-1][-1]
    ##print(a)
    for i in range(a.shape[0]-1, 0, -1):
        b[:i] -= np.tensordot(a[:i,i],b[i],axes=0)
        a[:i] -= np.tensordot(a[:i,i],a[i],axes=0)
    ##print(a)
    return b

Проверкой будет обращение матрицы

In [101]:
m = np.random.uniform(-5, 5, (3,3))
m

array([[-1.47600432,  1.89520442,  0.58423286],
       [-2.02375432,  2.71059684,  3.93034915],
       [ 1.86487964, -1.77960061, -3.79875538]])

In [102]:
k = sol(m, np.diag(np.ones(3)))
k

array([[-0.98682023,  1.84061737,  1.75260986],
       [-0.10701157,  1.34988459,  1.38018839],
       [-0.43431675,  0.27121368, -0.04943137]])

In [103]:
np.dot(m,k)

array([[ 1.00000000e+00, -3.05311332e-16, -1.00613962e-16],
       [ 0.00000000e+00,  1.00000000e+00, -5.82867088e-16],
       [ 0.00000000e+00,  2.22044605e-16,  1.00000000e+00]])