Разрешение СЛАУ с трёх диагональной матрицой и ненулевыми главными минорами.

In [2]:
import numpy as np

In [154]:
def sol(a, b):
    for i in range(a.shape[0]-1):
        gi = a[i+1][i]/a[i][i]
        a[i+1] = a[i+1] - a[i] * gi
        b[i+1] = b[i+1] - b[i] * gi
    for i in range(a.shape[0]-1, 0, -1): 
        b[:i] = b[:i] - b[i]/a[i][i] * a[:i, i]
        a[:i, i] = 0
        
    return a, b

In [155]:
Z = np.diag(np.arange(1, 5), k=-1) + np.diag(np.arange(1, 6), k=0) + np.diag(np.arange(1, 5), k=1)
Z

array([[1, 1, 0, 0, 0],
       [1, 2, 2, 0, 0],
       [0, 2, 3, 3, 0],
       [0, 0, 3, 4, 4],
       [0, 0, 0, 4, 5]])

In [156]:
k = sol(Z, np.array([1, 2, 3, 4, 5]))
k

(array([[ 1,  0,  0,  0,  0],
        [ 0,  1,  0,  0,  0],
        [ 0,  0, -1,  0,  0],
        [ 0,  0,  0, 13,  0],
        [ 0,  0,  0,  0,  3]]), array([0, 1, 0, 4, 2]))

In [143]:
x = np.zeros(6)
Z[:3, 4]

array([0, 0, 0])