Разрешение СЛАУ с трёх диагональной матрицой и ненулевыми главными минорами.

In [4]:
import numpy as np

In [21]:
def sol(m, b):
    a = m.copy()
    for i in range(a.shape[0]-1):
        b[i] = b[i]/a[i, i]
        a[i] = a[i]/a[i, i]
        ##gi = a[i+1][i]/a[i][i]
        b[i+1] = b[i+1] - b[i] * a[i+1,i]
        a[i+1] = a[i+1] - a[i] * a[i+1,i]
    b[-1]=b[-1]/a[-1][-1]
    a[-1]=a[-1]/a[-1][-1]
    for i in range(a.shape[0]-1, 0, -1):
        '''
        g = a[:i, i]/a[i][i]
        l = np.ones(i*b.shape[0].reshape(i,-1)
        print(l)
        l = np.dot(g.transpose(),b[i])
        print(g,b[i])
        '''
        print(a[i-1])
        b[:i]=b[:i] - np.tensordot(a[:i,i],b[i],axes=0)
        ##b[i-1] = b[i-1] - b[i] * a[i-1, i]
        a[:i, i] = 0
    return [b]

Проверкой будет обращение матрицы

In [22]:
Z = np.diag(np.arange(1, 3), k=-1) + np.diag(np.arange(1, 4), k=0) + np.diag(np.arange(1, 3), k=1)
Z

array([[1, 1, 0],
       [1, 2, 2],
       [0, 2, 3]])

In [23]:
k = sol(Z, np.diag(np.ones(3)))

[0 1 2]
[1 1 0]


In [24]:
np.dot(Z,k)

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]]])

In [25]:
Z[:2]

array([[1, 1, 0],
       [1, 2, 2]])